title = "Unqualified"
uri = "https://blog.flowthing.me"
homepage = "https://github.com/eerohele"
author = "Eero Helenius"
description = "A litany of cogitations on code and other things."
language = "en-us"
